dist: xenial
language: c++
sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
    - iverilog
    - llvm

before_install:
  - ls /usr/local/lib
  - ls /usr/local/include/  
  - dpkg -L z3
  - cmake .
  - make -j

script:
  - ./all-tests

compiler:
  - gcc

os:
- linux